import { FoodItem } from '@/types';
export const starterFoods: FoodItem[] = [
 {id:'boiled-egg',name:'Boiled egg',category:'Protein',servingType:'perPiece',defaultServingGrams:50,calories:78,protein:6.3,carbs:0.6,fat:5.3},
 {id:'egg-white',name:'Egg white',category:'Protein',servingType:'perPiece',defaultServingGrams:33,calories:17,protein:3.6,carbs:0.2,fat:0.1},
 {id:'cottage-cheese',name:'Low-fat cottage cheese / posni sir',category:'Dairy',servingType:'per100g',calories:82,protein:11,carbs:3.4,fat:2.3},
 {id:'whey',name:'Whey protein',category:'Protein',servingType:'per100g',calories:400,protein:80,carbs:8,fat:6},
 {id:'white-rice',name:'White rice cooked',category:'Carbs',servingType:'per100g',calories:130,protein:2.7,carbs:28.2,fat:0.3},
 {id:'brown-rice',name:'Brown rice cooked',category:'Carbs',servingType:'per100g',calories:112,protein:2.6,carbs:23,fat:0.9},
 {id:'pasta',name:'Pasta cooked',category:'Carbs',servingType:'per100g',calories:158,protein:5.8,carbs:30.9,fat:0.9},
 {id:'chicken',name:'Chicken breast',category:'Protein',servingType:'per100g',calories:165,protein:31,carbs:0,fat:3.6},
 {id:'turkey',name:'Turkey breast',category:'Protein',servingType:'per100g',calories:135,protein:29,carbs:0,fat:1.5},
 {id:'lean-beef',name:'Lean beef / junetina',category:'Protein',servingType:'per100g',calories:176,protein:26,carbs:0,fat:8},
 {id:'tuna',name:'Tuna in water',category:'Protein',servingType:'per100g',calories:116,protein:26,carbs:0,fat:1},
 {id:'salmon',name:'Salmon',category:'Protein',servingType:'per100g',calories:208,protein:20,carbs:0,fat:13},
 {id:'greek-yogurt',name:'Greek yogurt',category:'Dairy',servingType:'per100g',calories:59,protein:10,carbs:3.6,fat:0.4},
 {id:'skyr',name:'Skyr',category:'Dairy',servingType:'per100g',calories:63,protein:11,carbs:4,fat:0.2},
 {id:'cucumber',name:'Cucumber',category:'Vegetable',servingType:'per100g',calories:15,protein:0.7,carbs:3.6,fat:0.1},
 {id:'tomato',name:'Tomato',category:'Vegetable',servingType:'per100g',calories:18,protein:0.9,carbs:3.9,fat:0.2},
 {id:'lettuce',name:'Lettuce',category:'Vegetable',servingType:'per100g',calories:15,protein:1.4,carbs:2.9,fat:0.2},
 {id:'mixed-salad',name:'Mixed salad',category:'Vegetable',servingType:'per100g',calories:20,protein:1.1,carbs:4,fat:0.2},
 {id:'green-beans',name:'Green beans / mahune',category:'Vegetable',servingType:'per100g',calories:35,protein:1.9,carbs:7.9,fat:0.3},
 {id:'broccoli',name:'Broccoli',category:'Vegetable',servingType:'per100g',calories:35,protein:2.4,carbs:7.2,fat:0.4},
 {id:'zucchini',name:'Zucchini',category:'Vegetable',servingType:'per100g',calories:17,protein:1.2,carbs:3.1,fat:0.3},
 {id:'potato',name:'Potato cooked',category:'Carbs',servingType:'per100g',calories:87,protein:1.9,carbs:20.1,fat:0.1},
 {id:'sweet-potato',name:'Sweet potato',category:'Carbs',servingType:'per100g',calories:86,protein:1.6,carbs:20.1,fat:0.1},
 {id:'oats',name:'Oats',category:'Carbs',servingType:'per100g',calories:389,protein:16.9,carbs:66.3,fat:6.9},
 {id:'banana',name:'Banana',category:'Fruit',servingType:'per100g',calories:89,protein:1.1,carbs:22.8,fat:0.3},
 {id:'apple',name:'Apple',category:'Fruit',servingType:'per100g',calories:52,protein:0.3,carbs:13.8,fat:0.2},
 {id:'olive-oil',name:'Olive oil',category:'Fat',servingType:'per100g',calories:884,protein:0,carbs:0,fat:100},
 {id:'avocado',name:'Avocado',category:'Fat',servingType:'per100g',calories:160,protein:2,carbs:8.5,fat:14.7}
];
